### ISSUE TITLE
Auto-Drive speed control.

### ISSUE THREAD

**Issue by oneswitch** [Rezmason/drivey#1]
It would be fantastic if the auto-drive and manual drive top speed could be adjusted by the user, from fast to a crawl.

Reasons?

1. A mellower driving experience.
2. A less hectic screen-saver/kinetic display.
3. Improved accessibility.

**Comment by Rezmason** [comment]
This was a particularly solid idea, so it's in. The auto drive button now allows the player to choose between manual control and three auto drive speeds.

Car speed can also be influenced by holding down the up and down arrow keys— a holdover from the original Drivey— which will likely be mapped to more tablet-friendly inputs in the future.

**Comment by oneswitch** [comment]
Top man. I'd like to see a bigger difference in speed though ideally. Slowest should be really nice and slow. Slowest still feels like I'm doing 50mph. Maybe 20 mph / 40 mph / 60 mph the difference in feel?

**Comment by Rezmason** [comment]
Updated.

**Comment by oneswitch** [comment]
Nice. :)
