### ISSUE TITLE
Accessibility options via a button

### ISSUE THREAD

**Issue by Rezmason** [Rezmason/drivey#5]
From [Barrie Ellis](oneswitch.org.uk) on Twitter:

> For one-switch play, if someone needs access to the menus, they seem easy enough to use with a mouse emulator - so not to worry there. If there was a one-switch drive mode, where you could click on a large target / the whole screen to steer left / right alternatively that would be lovely.

> For eye gaze, if it could be controlled using the mouse pointer (position on the left side of the screen for left and vice versa for right, with a big dead zone in the middle... That would be great.

> Sounds would aid understanding for some. Being able to turn off SFX from music / ambient sounds really handy.

> Keyboard control over menus would be great too. Essential for blind players. But anything would be really appreciated.

Current game plan: a "Control Mode" button, added to the button set, that switches between "classic", "one switch" and "eye gaze". "one switch" would map a single click and double click on the whole screen to steering left and right; "eye gaze" would map mouse position in regions near the screen's edge to steering left and right.

Also, if sounds are added, then an "Audio Mode" button would switch between no audio, sound effects, and an audio accessibility feature, if there is such a thing.

**Comment by oneswitch** [comment]
Seems you already have one-switch driving. :) 

Just click on the "drive on [the left/right]". Works really well if you have the dash switched off.

**Comment by neauoire** [comment]
Each theme/style should have it's own number, `1`, `2`, `3`...

**Comment by neauoire** [comment]
I suggest `h` to hide the dashboard.

**Comment by Rezmason** [comment]
@oneswitch I've finished adding explicit support for touch screen, arrow key, one switch and eye gaze input formats. One switch and eye gaze both have cruise control permanently on, but they wire the steering wheel to the control schemes you described on Twitter; they each have sensitivities for manual and auto steering that I can adjust until they feel right. Eye gaze's dead zone is the middle 90% of the screen.

Let me know if they need refinement!
