### ISSUE TITLE
Off-line version

### ISSUE THREAD

**Issue by oneswitch** [Rezmason/drivey#6]
For people with bad internet connection, it would be great to have an off-line version. Perfect for shows too.

**Comment by neauoire** [comment]
You can download an offline version [here](https://github.com/Rezmason/drivey/archive/master.zip).

**Comment by Rezmason** [comment]
Yes, downloading the ZIP file of the project seems like the most surefire approach. I'll add clear instructions to the readme though

**Comment by Rezmason** [comment]
Readme updated.
